name: Docker Drift Check

# When to run this workflow
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build test container
        run: |
          docker run -d --name test-container ubuntu sleep 60
          docker exec test-container apt-get update && docker exec test-container apt-get install -y curl

      - name: Run DockDrift
        run: |
          chmod +x drift.sh
          ./drift.sh ubuntu:latest test-container

